title: "Xingzhi Zhou"
description: Master student at Tokyo Institute of Technology
email: Xingzhi06Zhou@gmail.com
github_username: XingzhiZhou

author_website: https://scholar.google.com/citations?user=fg5DcoIAAAAJ&hl=en
remote_theme: academic

